### ISSUE TITLE
Incorrect PROC typedef

### ISSUE THREAD

**Issue by msiglreith** [brendanzab/gl-rs#438]
The definition of [`PROC`](https://github.com/brendanzab/gl-rs/blob/master/gl_generator/generators/templates/types/wgl.rs#L29) causes issues on the latest [nightly](https://github.com/rust-lang/rust/issues/46182). The functions aren't allow to be zero, which rust makes use by annotating them with non-null. Unfortunately, the returned functions by `wglGetProcAddress` can be zero (e.g GL1.1 functions). Glutin currently checks if the functions are zero else it queries the addresses via `kernel32::GetProcAddress`. The rust compiler optimizes this call away as it assumes we don't have null functions.

The proposed solution is to replace `extern "system" fn()` with `*const ()`, which also fixes the issue for me locally.

**Comment by tomaka** [comment]
The fix makes sense to me.

**Comment by brendanzab** [comment]
Yeah, as you can see from the comment I had no idea what I was doing when I was translating those type defs! What does `PROC` look like in use? Would people have to transmute to `*const ()`? 

I'm also guessing we would have to to a major release seeing as its an API change.

**Comment by retep998** [comment]
You can use what winapi does as an example of how it should be done.

https://github.com/retep998/winapi-rs/blob/b6eed13c28a8808bfdc54cdf50c4498132ce9176/src/shared/minwindef.rs#L76-L82

**Comment by brendanzab** [comment]
@retep998: That's still using a void enum - is it still UB to use that?

```rust
pub enum __some_function {}
/// Pointer to a function with unknown type signature.
pub type FARPROC = *mut __some_function;
```

cc. @eddyb

**Comment by brendanzab** [comment]
Wondering if we should just depend on winapi somehow for these types rather than having to maintain our own, but that's a separate issue 🤔

**Comment by eddyb** [comment]
The canonical equivalent for C function pointers into Rust is `Option<extern fn()>`, and that is precisely what `bindgen` generates for them.

**Comment by retep998** [comment]
Raw pointers to uninhabited times are legal and well defined (because they can be created in safe code). You just can never ever deref it. All you have to do is transmute the raw pointer to `Option<unsafe extern fn()>` with the correct signature. The reason `GetProcAddress` returns a raw pointer to an uninhabited type instead of an `Option<unsafe extern fn()>` directly is because there is no fixed signature that the functions it returns will use. Otherwise someone could accidentally call the function pointer without first casting it to the correct type (which is bad).

**Comment by McGittyHub** [comment]
* friendly bump * 

Any ETA on this?

**Comment by McGittyHub** [comment]
Is this going to be fixed any time soon? 

Currently you cannot run release builds of programs using gl-rs on windows using current nightly rustc.

\* yet another friendly bump \*

**Comment by brendanzab** [comment]
Sorry for delays, `gl_generator v0.7.0` and `gl v0.7.0` should be published now with the fixes!

**Comment by albel727** [comment]
I've just encountered the very same typing bug resulting in segmentation fault due to  `__GLXextFuncPtr` type in glx template, which is used as a return type for `GetProcAddress()`.

https://github.com/brendanzab/gl-rs/blob/dc92a668167f14b472bf35699d2e98967b5688bd/gl_generator/generators/templates/types/glx.rs#L18

Fixing the type fixes the crash for me.

**Comment by albel727** [comment]
So, it's been two weeks. Can we fix it for GLX too? Should I open a new issue?
