### ISSUE TITLE
glShaderSource has different behavior in release mode

### ISSUE THREAD

**Issue by neonmoe** [brendanzab/gl-rs#469]
Rust version: 1.29.0
gl version: 0.10.0

Expected behavior: When I call gl::ShaderSource, it uploads the source found behind the pointer.
Actual behavior: In debug mode (`cargo run`) this works fine, but in release mode (`cargo run --release`) the shader just ends up containing garbage data according to GetShaderSource.

I'm calling glShaderSource with parameters I've initialized outside of the unsafe block, so I would assume my code shouldn't cause this.

Code:
```rust
let create_shader = |t: GLuint, source: &'static str| {
    let len = [source.len() as GLint].as_ptr();
    let source = [source.as_ptr() as *const GLchar].as_ptr();
    let shader;
    unsafe {
        shader = gl::CreateShader(t);

        // FIXME: This doesn't actually upload the source when ran with --release.
        gl::ShaderSource(shader, 1, source, len);

        let mut uploaded = [0; 10];
        gl::GetShaderSource(shader, 10, ptr::null_mut(), uploaded.as_mut_ptr());
        // Debug mode prints out (and this matches the actual string): [35, 118, 101, 114, 115, 105, 111, 110, 32, 0] 
        // Release mode prints out (and changes every run): [-24, -24, -100, -124, -45, 0, 0, 0, 0, 0]
        println!("{:?}", uploaded);

        gl::CompileShader(shader);
    }
    shader
};
```

It's part of [this project](https://git.neon.moe/neon/fungui/src/branch/master/src/renderer.rs) in case more context is needed.

**Comment by brendanzab** [comment]
Weird - I wonder if this is running into some UB (undefined behaviour) that LLVM is now taking advantage of? I'm afraid I'm a bit out of my depth on this one.

cc. @kvark

**Comment by brendanzab** [comment]
Might be interesting to compare the assembly output at both optimization levels.

**Comment by kvark** [comment]
Let's keep this open please. Unsafety issues like this are difficult to discover and should get proper treatment.

**Comment by kvark** [comment]
@neonmoe is there a particular revision I could grab from your project to reproduce this on my side?

**Comment by kvark** [comment]
Also please note that this code is incorrect:
```rust
gl::GetShaderSource(shader, 10, ptr::null_mut(), uploaded.as_mut_ptr());
```
The length passed doesn't include the null terminator, which is *still* written by the GL driver. So this line causes out of bounds writes.

**Comment by kvark** [comment]
Thank you, that's a good repro case. I had a chance to look at it.
Moral of the story - don't play with pointers!

```rust
    let len = [source.len() as GLint].as_ptr();
```
Here, rust sees that you need a local fixed size array (of size 1) on the stack, and it's happily allocating it. However, it's not getting any name assigned, so it's lifetime is contained within this very line... as soon as you take `as_ptr()` of it - POOF! it's gone!
```rust
let source = [source.as_ptr() as *const GLchar].as_ptr();
```
The same thing happens here. In Release (starting with `opt-level = 1`), the compiler is happily re-using the same stack space (since, as we noted, it's lifetime is a single line of code), thus you end up passing the same pointer for both the source and the length to GL :)

With this, I think the issue can be closed. It's not a bug in gl-rs :tada:

**Comment by neonmoe** [comment]
Oh, that makes a lot of sense. Thank you for the explanation!
